# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'student.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_student(object):
    def setupUi(self, student):
        student.setObjectName("student")
        student.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        student.setFont(font)
        self.centralwidget = QtWidgets.QWidget(student)
        self.centralwidget.setObjectName("centralwidget")
        self.backbutton = QtWidgets.QPushButton(self.centralwidget)
        self.backbutton.setGeometry(QtCore.QRect(10, 10, 93, 28))
        self.backbutton.setObjectName("backbutton")
        student.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(student)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 29))
        self.menubar.setObjectName("menubar")
        student.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(student)
        self.statusbar.setObjectName("statusbar")
        student.setStatusBar(self.statusbar)

        self.retranslateUi(student)
        QtCore.QMetaObject.connectSlotsByName(student)

    def retranslateUi(self, student):
        _translate = QtCore.QCoreApplication.translate
        student.setWindowTitle(_translate("student", "学生"))
        self.backbutton.setText(_translate("student", "返回"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    student = QtWidgets.QMainWindow()
    ui = Ui_student()
    ui.setupUi(student)
    student.show()
    sys.exit(app.exec_())
