# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'system.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets



class Ui_system(object):
    def setupUi(self, system):
        system.setObjectName("system")
        system.resize(800, 624)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        system.setFont(font)
        self.centralwidget = QtWidgets.QWidget(system)
        self.centralwidget.setObjectName("centralwidget")
        self.studentbutton = QtWidgets.QPushButton(self.centralwidget)
        self.studentbutton.setGeometry(QtCore.QRect(310, 120, 171, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.studentbutton.setFont(font)
        self.studentbutton.setObjectName("studentbutton")
        self.teacherbutton = QtWidgets.QPushButton(self.centralwidget)
        self.teacherbutton.setGeometry(QtCore.QRect(310, 220, 171, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.teacherbutton.setFont(font)
        self.teacherbutton.setObjectName("teacherbutton")
        self.administratorbutton = QtWidgets.QPushButton(self.centralwidget)
        self.administratorbutton.setGeometry(QtCore.QRect(310, 320, 171, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.administratorbutton.setFont(font)
        self.administratorbutton.setObjectName("administratorbutton")
        system.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(system)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 29))
        self.menubar.setObjectName("menubar")
        system.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(system)
        self.statusbar.setObjectName("statusbar")
        system.setStatusBar(self.statusbar)

        self.retranslateUi(system)
        QtCore.QMetaObject.connectSlotsByName(system)



    def retranslateUi(self, system):
        _translate = QtCore.QCoreApplication.translate
        system.setWindowTitle(_translate("system", "教学管理系统"))
        self.studentbutton.setText(_translate("system", "学生"))
        self.teacherbutton.setText(_translate("system", "教师"))
        self.administratorbutton.setText(_translate("system", "管理员"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    system = QtWidgets.QMainWindow()
    ui = Ui_system()
    ui.setupUi(system)
    system.show()
    sys.exit(app.exec_())
