# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'teacher.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_teacher(object):
    def setupUi(self, teacher):
        teacher.setObjectName("teacher")
        teacher.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        teacher.setFont(font)
        self.centralwidget = QtWidgets.QWidget(teacher)
        self.centralwidget.setObjectName("centralwidget")
        self.backbutton = QtWidgets.QPushButton(self.centralwidget)
        self.backbutton.setGeometry(QtCore.QRect(10, 10, 93, 28))
        self.backbutton.setObjectName("backbutton")
        teacher.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(teacher)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 29))
        self.menubar.setObjectName("menubar")
        teacher.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(teacher)
        self.statusbar.setObjectName("statusbar")
        teacher.setStatusBar(self.statusbar)

        self.retranslateUi(teacher)
        QtCore.QMetaObject.connectSlotsByName(teacher)

    def retranslateUi(self, teacher):
        _translate = QtCore.QCoreApplication.translate
        teacher.setWindowTitle(_translate("teacher", "教师"))
        self.backbutton.setText(_translate("teacher", "返回"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    teacher = QtWidgets.QMainWindow()
    ui = Ui_teacher()
    ui.setupUi(teacher)
    teacher.show()
    sys.exit(app.exec_())
