# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'teacher.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *

import sys
import pymysql

class Ui_teacher(object):
    # 获得选课学生信息
    def teacher2student(self):
        self.tableWidget.clearContents()
        tname = self.teacherlineEdit.text()
        cur = self.con.cursor()
        query = 'select tno from teacher where tname=%s'
        if not tname:
            QMessageBox.warning(self, '警告', '请输入教师姓名')
        elif not cur.execute(query,[tname]):
            QMessageBox.warning(self, '警告', '该姓名不存在')
        else:
            query = 'select studentno,sname,courseno,scheduleno,score,teacherno from student_courses where teacherno in (select tno from teacher where tname=%s)'
            cur.execute(query, [tname])
            data = cur.fetchall()
            x = 0
            for i in data:
                y = 0
                for j in i:
                    self.tableWidget.setItem(x,y, QtWidgets.QTableWidgetItem(str(data[x][y])))
                    y = y + 1
                x = x + 1
    
    # 录入成绩
    def scoreInsert(self):
        sno,scheduleno,score = self.lineEdit_sno.text(),self.lineEdit_cno.text(),self.lineEdit_score.text()
        cur = self.con.cursor()
        if not sno or not scheduleno or not score:
            QMessageBox.warning(self, '警告', '请输入学号、开课号和成绩')
        elif not cur.execute('select * from choose where studentno=%s and scheduleno=%s',[sno,scheduleno]):
            QMessageBox.warning(self, '警告', '请输入学号或开课号错误')
        else:
            cur.execute('update choose set score=%s where studentno=%s and scheduleno=%s',[int(score),sno,scheduleno])
            self.con.commit()
            QMessageBox.information(self, '成功', '成绩已录入')
        self.lineEdit_sno.clear()
        self.lineEdit_cno.clear()
        self.lineEdit_score.clear()



    def setupUi(self, teacher, con):
        self.con = con
        teacher.setObjectName("teacher")
        teacher.resize(800, 625)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        teacher.setFont(font)
        self.centralwidget = QtWidgets.QWidget(teacher)
        self.centralwidget.setObjectName("centralwidget")
        self.backbutton = QtWidgets.QPushButton(self.centralwidget)
        self.backbutton.setGeometry(QtCore.QRect(10, 10, 93, 28))
        self.backbutton.setObjectName("backbutton")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 70, 750, 280))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(100)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 360, 361, 231))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit_sno = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_sno.setText("")
        self.lineEdit_sno.setObjectName("lineEdit_sno")
        self.gridLayout_3.addWidget(self.lineEdit_sno, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEdit_cno = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_cno.setText("")
        self.lineEdit_cno.setObjectName("lineEdit_cno")
        self.gridLayout_2.addWidget(self.lineEdit_cno, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.lineEdit_score = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_score.setText("")
        self.lineEdit_score.setObjectName("lineEdit_score")
        self.gridLayout_13.addWidget(self.lineEdit_score, 1, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_16.setObjectName("label_16")
        self.gridLayout_13.addWidget(self.label_16, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_13)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.scoreInsertButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.scoreInsertButton.setObjectName("scoreInsertButton")
        self.horizontalLayout.addWidget(self.scoreInsertButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(120, 10, 241, 31))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.teacherlineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.teacherlineEdit.setObjectName("teacherlineEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.teacherlineEdit)
        self.studentpushButton = QtWidgets.QPushButton(self.centralwidget)
        self.studentpushButton.setGeometry(QtCore.QRect(380, 10, 102, 32))
        self.studentpushButton.setObjectName("studentpushButton")
        teacher.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(teacher)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 29))
        self.menubar.setObjectName("menubar")
        teacher.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(teacher)
        self.statusbar.setObjectName("statusbar")
        teacher.setStatusBar(self.statusbar)

        self.retranslateUi(teacher)
        QtCore.QMetaObject.connectSlotsByName(teacher)

        # operation
        self.studentpushButton.clicked.connect(self.teacher2student)
        self.scoreInsertButton.clicked.connect(self.scoreInsert)

    def retranslateUi(self, teacher):
        _translate = QtCore.QCoreApplication.translate
        teacher.setWindowTitle(_translate("teacher", "教师"))
        self.backbutton.setText(_translate("teacher", "返回"))
        self.label.setText(_translate("teacher", "  录入成绩"))
        self.label_5.setText(_translate("teacher", "   学号   "))
        self.label_3.setText(_translate("teacher", "开课班号"))
        self.label_16.setText(_translate("teacher", "   成绩   "))
        self.scoreInsertButton.setText(_translate("teacher", "插入"))
        self.label_4.setText(_translate("teacher", "教师名称"))
        self.studentpushButton.setText(_translate("teacher", "查询学生"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("teacher", "studentno"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("teacher", "studentname"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("teacher", "courseno"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("teacher", "scheduleno"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("teacher", "score"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("teacher", "teacherno"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    teacher = QtWidgets.QMainWindow()
    ui = Ui_teacher()
    ui.setupUi(teacher)
    teacher.show()
    sys.exit(app.exec_())
